import{a as v,S as B,i as l}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const M="50314234-ba813915cbcdccb3e2319b70f",R="https://pixabay.com/api/";function p(s,r=1,e=40){const n={key:M,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:e};return v.get(R,{params:n})}const m=document.querySelector(".gallery"),g=document.querySelector(".loader"),y=document.getElementById("loadMoreBtn");let f=null;function b(s){const r=s.map(e=>`
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" />
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </a>
    `).join("");m.insertAdjacentHTML("beforeend",r),f?f.refresh():f=new B(".gallery a")}function S(){m.innerHTML=""}function L(){g.classList.remove("hidden")}function i(){g.classList.add("hidden")}function w(){y.classList.remove("hidden")}function h(){y.classList.add("hidden")}const E=document.querySelector("#searchForm"),q=document.querySelector("#searchInput"),$=document.getElementById("loadMoreBtn");let a="",d=1,c=40;E.addEventListener("submit",async s=>{if(s.preventDefault(),a=q.value.trim(),!!a){d=1,c=40,S(),h(),L();try{const e=(await p(a,d,c)).data.hits;if(e.length===0){l.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),i();return}b(e),i(),w(),c=20}catch(r){console.error("Fetch error:",r),l.error({title:"Error",message:"An error occurred while fetching images.",position:"topRight"}),i()}}});$.addEventListener("click",async()=>{d++,L(),h();try{const r=(await p(a,d,c)).data.hits;if(r.length===0){l.info({title:"No More Results",message:"No more images found.",position:"topRight"}),i(),h();return}b(r),i(),w();const e=document.querySelector(".gallery a");if(e){const n=e.getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}}catch(s){console.error("Fetch error:",s),l.error({title:"Error",message:"We are sorry, but you have reached the end of search results.",position:"topRight"}),i()}});
//# sourceMappingURL=index.js.map
