import{a as v,S as B,i as c}from"./assets/vendor-1AYLTIiv.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const E="50314234-ba813915cbcdccb3e2319b70f",w="https://pixabay.com/api/";function h(s,t=1,r=40){const a={key:E,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:r};return v.get(w,{params:a})}const m=document.querySelector(".gallery");document.getElementById("loader");document.getElementById("loaderBelow");const p=document.getElementById("loadMoreBtn");let u=null;function g(s){const t=s.map(r=>`
      <a href="${r.largeImageURL}" class="gallery-item">
        <img src="${r.webformatURL}" alt="${r.tags}" />
        <div class="info">
          <p><b>Likes:</b> ${r.likes}</p>
          <p><b>Views:</b> ${r.views}</p>
          <p><b>Comments:</b> ${r.comments}</p>
          <p><b>Downloads:</b> ${r.downloads}</p>
        </div>
      </a>
    `).join("");m.insertAdjacentHTML("beforeend",t),u?u.refresh():u=new B(".gallery a")}function M(){m.innerHTML=""}function y(){loader.classList.remove("hidden")}function n(){loader.classList.add("hidden")}function b(){p.classList.remove("hidden")}function f(){p.classList.add("hidden")}const I=document.querySelector("#searchForm"),S=document.querySelector("#searchInput"),$=document.getElementById("loadMoreBtn");let i="",l=1;const L=40;I.addEventListener("submit",s=>{s.preventDefault(),i=S.value.trim(),i&&(l=1,M(),f(),y(),h(i,l,L).then(t=>{const r=t.data.hits;if(r.length===0){c.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"}),n();return}g(r),n(),b()}).catch(t=>{console.error("Fetch error:",t),c.error({title:"Error",message:"We are sorry, but you have reached the end of search results.",position:"topRight"}),n()}))});$.addEventListener("click",()=>{l++,y(),f(),h(i,l,L).then(s=>{const t=s.data.hits;if(t.length===0){c.info({title:"No More Results",message:"No more images found."}),n(),f();return}g(t),n(),b()}).catch(s=>{console.error("Fetch error:",s),c.error({title:"Error",message:"We are sorry, but you have reached the end of search results.",position:"topRight"}),n()})});
//# sourceMappingURL=index.js.map
